# Generated by Django 3.1.4 on 2020-12-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20201210_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basics.page')),
                ('likes', models.IntegerField()),
            ],
            bases=('basics.page',),
        ),
    ]
