# Generated by Django 3.1.4 on 2020-12-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_auto_20201210_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='like',
            name='page_in',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basics.page'),
        ),
    ]
